name: Build and deploy Backend to Azure Web App (OIDC)

on:
  push:
    branches:
      - main
    paths:
      - 'server/**' # Käynnistyy vain kun backend-koodia muutetaan
  workflow_dispatch:

permissions:
  id-token: write # Vaaditaan OIDC JWT-tokenin pyytämiseen
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build --if-present

      - name: Log in to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BBB3F18F0158459695AE20B126F270DF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C76322D94AD94094B86C4363E17F76F0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_44031F5529844CF58B167269636A15F1 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Leffapiiri-api'
          package: '.' # Julkaisee server-kansion sisällön
